# Generated by Django 4.2.2 on 2023-09-01 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat_and_acc',
            name='what_acc',
        ),
        migrations.RemoveField(
            model_name='chat_and_acc',
            name='what_chat',
        ),
        migrations.RemoveField(
            model_name='chat_valid',
            name='what_chat',
        ),
        migrations.RemoveField(
            model_name='message',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='message',
            name='receiver',
        ),
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['party', 'last_name'], 'permissions': (('staff_', 'Принадлежность к персоналу'), ('transaction', 'Может создавать транзакции'), ('transaction_base', 'Может совершать переводы'), ('register', 'Может регистрировать пользователей'), ('edit_users', 'Может изменять пользователей'), ('ant_edit', 'Может изменять объявления'), ('meria', 'Мэрия в банке'))},
        ),
        migrations.DeleteModel(
            name='chat',
        ),
        migrations.DeleteModel(
            name='chat_and_acc',
        ),
        migrations.DeleteModel(
            name='chat_valid',
        ),
        migrations.DeleteModel(
            name='message',
        ),
    ]
