# Generated by Django 4.2.2 on 2023-09-13 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='sign',
            field=models.CharField(choices=[('p2p+', 'Личный перевод'), ('dining_services+', 'Дежурный в столовой'), ('activity+', 'Активность'), ('salary+', 'Зарплата'), ('fee+', 'Гонорар'), ('purchase-', 'Покупка'), ('fine-', 'Штраф')], default='+', max_length=20, verbose_name='Тип транзакции:'),
        ),
    ]
