# Generated by Django 4.2.2 on 2023-09-01 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_remove_chat_and_acc_what_acc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='theme_self',
            field=models.CharField(choices=[('default', 'По-умолчанию'), ('table-primary', 'Голубой'), ('table-secondary', 'Серый'), ('table-success', 'Зелёный'), ('table-danger', 'Красный'), ('table-warning', 'Жёлтый'), ('table-info', 'Светло-зелёный'), ('table-light', 'Светлая'), ('table-dark', 'Тёмная'), ('a_default', 'По-умолчанию (аналог)'), ('p-3 mb-2 bg-primary text-white', 'Голубой (аналог)'), ('p-3 mb-2 bg-secondary text-white', 'Серый (аналог)'), ('p-3 mb-2 bg-success text-white', 'Зелёный (аналог)'), ('p-3 mb-2 bg-danger text-white', 'Красный (аналог)'), ('p-3 mb-2 bg-warning text-dark', 'Жёлтый (аналог)'), ('p-3 mb-2 bg-info text-dark', 'Светло-зелёный (аналог)'), ('p-3 mb-2 bg-light text-dark', 'Светлая (аналог)'), ('p-3 mb-2 bg-dark text-white', 'Тёмная (аналог)'), ('p-3 mb-2 bg-primary bg-gradient text-white', 'Голубой (аналог, градиент)'), ('p-3 mb-2 bg-secondary bg-gradient text-white', 'Серый (аналог, градиент)'), ('p-3 mb-2 bg-success bg-gradient text-white', 'Зелёный (аналог, градиент)'), ('p-3 mb-2 bg-danger bg-gradient text-white', 'Красный (аналог, градиент)'), ('p-3 mb-2 bg-warning bg-gradient text-dark', 'Жёлтый (аналог, градиент)'), ('p-3 mb-2 bg-info bg-gradient text-dark', 'Светло-зелёный (аналог, градиент)'), ('p-3 mb-2 bg-light bg-gradient text-dark', 'Светлая (аналог, градиент)'), ('p-3 mb-2 bg-dark bg-gradient text-white', 'Тёмная (аналог, градиент)')], default='default', help_text='Как это выглядит, можно посмотреть ниже.', max_length=50, verbose_name='Тема:'),
        ),
    ]
