# Generated by Django 4.2.7 on 2024-01-26 15:48

import datetime
from django.db import migrations, models
import django.db.models.deletion
import messenger.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='chat',
            fields=[
                ('cnt', models.IntegerField(default=1, editable=False)),
                ('name', models.CharField(default='', max_length=50, verbose_name='Название чата:')),
                ('description', models.CharField(default='', max_length=500, verbose_name='Описание чата:')),
                ('anonim', models.BooleanField(default=False, verbose_name='Если вы хотите сделать чат анонимным, поставьте здесь галочку. Этот параметр неизменяем.')),
                ('anonim_legacy', models.BooleanField(default=False, verbose_name='Поставьте галочку, если хотите разрешить участникам отправлять анонимные сообщения.')),
                ('avaliable_resend_messages', models.BooleanField(default=True, verbose_name='Поставьте галочку, если хотите разрешить пересылать сообщения из этого чата.')),
                ('chat_ico', models.ImageField(upload_to='', verbose_name='Иконка чата:')),
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Уникальный ID чата.', primary_key=True, serialize=False)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator_chat', to='bank.account', verbose_name='Создатель:')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='message',
            fields=[
                ('date', models.DateField(default=datetime.date(1, 1, 1), verbose_name='Дата:')),
                ('time', models.TimeField(default=datetime.time(0, 0), verbose_name='Время:')),
                ('text', messenger.models.EncryptedTextField(verbose_name='Текст:')),
                ('anonim', models.BooleanField(default=False, verbose_name='Если вы хотите отправить это сообщение анонимно, поставьте здесь галочку.')),
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Уникальный ID сообщения.', primary_key=True, serialize=False)),
                ('date_of_edit', models.DateField(default=datetime.date(1, 1, 1), verbose_name='Дата последнего измененния:')),
                ('time_of_edit', models.TimeField(default=datetime.time(0, 0), verbose_name='Время последнего изменения:')),
                ('editable', models.BooleanField(default=True, editable=False)),
                ('history', models.BooleanField(default=False, editable=False)),
                ('anonim_legacy', models.BooleanField(default=False, editable=False)),
                ('answer_for', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='messenger.message', verbose_name='Ответ на сообщение:')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bank.account', verbose_name='Отправитель:')),
                ('receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='messenger.chat', verbose_name='Получатель:')),
            ],
            options={
                'ordering': ['-date', '-time'],
            },
        ),
        migrations.CreateModel(
            name='chat_valid',
            fields=[
                ('avaliable', models.BooleanField(default=True, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Уникальный ID.', primary_key=True, serialize=False)),
                ('list_members', messenger.models.ListField(default=[], null=True, verbose_name='Список ID участников:')),
                ('list_messages', messenger.models.ListField(default=[], null=True, verbose_name='Список ID сообщений:')),
                ('what_chat', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='messenger.chat', verbose_name='Чат:')),
            ],
        ),
        migrations.CreateModel(
            name='chat_and_acc',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Уникальный ID.', primary_key=True, serialize=False)),
                ('readen', models.BooleanField(default=False, editable=False)),
                ('what_acc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bank.account', verbose_name='Аккаунт:')),
                ('what_chat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='messenger.chat', verbose_name='Чат:')),
            ],
        ),
        migrations.CreateModel(
            name='announcement',
            fields=[
                ('number', models.IntegerField(default=0, verbose_name='Номер в списке:')),
                ('name', models.TextField(max_length=50, verbose_name='Название:')),
                ('text', models.TextField(max_length=5000, verbose_name='Текст:')),
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Уникальный ID.', primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=False, verbose_name='Объявление принято?')),
                ('picture', models.ImageField(null=True, upload_to='', verbose_name='Картинка:')),
                ('orientation', models.IntegerField(choices=[(0, 'Горизонтально'), (1, 'Вертикально'), (2, 'Квадрат')], default=0, verbose_name='Ориентация:')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bank.account', verbose_name='Отправитель:')),
            ],
            options={
                'ordering': ['-number'],
            },
        ),
    ]
